name: Server CI
on:
  pull_request_target:
    paths:
      - "server/**"
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Set up golang
        uses: actions/setup-go@v3
        with:
          go-version: '^1.19.5'
      - name: Install gotestsum
        run: go install gotest.tools/gotestsum@latest
      - name: Run domain tests
        run: |
          cd server
          CHANGED=$(git diff --name-only ${{ github.event.workflow_run.head_sha }} | grep -q 'domain')
          if [ -n $CHANGED ]; then
            echo "Found changes in domain layer"
            make test-domain
          else
            echo "No test found in domain layer"
          fi
      - name: Run application tests
        run: |
          cd server
          CHANGED=$(git diff --name-only ${{ github.event.workflow_run.head_sha }} | grep -q 'application')
          if [ -n $CHANGED ]; then
            echo "Found changes in application layer"
            make test-app
          else
            echo "No test found in application layer"
          fi
      - name: Run infrastructure tests
        run: |
          cd server
          CHANGED=$(git diff --name-only ${{ github.event.workflow_run.head_sha }} | grep -q 'infrastructure')
          if [ -n $CHANGED ]; then
            echo "Found changes in infrastructure layer"
            make test-infra
          else
            echo "No test found in infrastructure layer"
          fi
