name: Server CI
on:
  workflow_dispatch:
  pull_request_target:
    paths:
      - "server/**"
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Set up golang
        uses: actions/setup-go@v3
        with:
          go-version: '^1.19.5'
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          working-directory: server
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        layer: [app, domain, infra]
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Set up golang
        uses: actions/setup-go@v3
        with:
          go-version: '^1.19.5'
      - name: Install gotestsum
        run: go install gotest.tools/gotestsum@latest
      - name: Run domain tests
        if: matrix.layer == 'domain'
        run: |
          cd server
          make test-domain
      - name: Run app tests
        if: matrix.layer == 'app'
        run: |
          cd server
          make test-app
      - name: Run infra tests
        if: matrix.layer == 'infra'
        run: |
          cd server
          make test-infra
