name: Server CI
on:
  push:
    branches:
      - main
  pull_request_target:
    paths:
      - "server/**"
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Set up golang
        uses: actions/setup-go@v3
        with:
          go-version: '^1.19.5'
      - name: Install gotestsum
        run: go install gotest.tools/gotestsum@latest
      - name: Run domain tests
        run: |
          cd server
          git diff --name-only HEAD~1 | grep 'server/domain' && make test-domain || echo "No tests to run"
      - name: Run application tests
        run: |
          cd server
          git diff --name-only HEAD~1 | grep -q 'server/application' && make test-app || echo "No tests to run"
      - name: Run infrastructure tests
        run: |
          cd server
          git diff --name-only HEAD~1 | grep -q 'server/infrastructure' && make test-infra || echo "No tests to run"
